### ISSUE TITLE
Need a repo tag for 0.0.2 to support bower

### ISSUE THREAD

**Issue by paullang** [adonespitogo/angular-loading-spinner#4]
I tried to reference 0.0.2 in bower.json, but it only found 0.0.1.

bower install
bower not-cached    git://github.com/adonespitogo/angular-loading-spinner.git#~0.0.2
bower resolve       git://github.com/adonespitogo/angular-loading-spinner.git#~0.0.2
bower ENORESTARGET  No tag found that was able to satisfy ~0.0.2

Additional error details:
Available versions: 0.0.1

I think you need to create a git tag for 0.0.2 to support bower finding the particular versions.

**Comment by adonespitogo** [comment]
Pushed tag v0.0.2
