### ISSUE TITLE
Prevent user interaction

### ISSUE THREAD

**Issue by jgribonvald** [adonespitogo/angular-loading-spinner#5]
Is there a way to prevent user interaction during loading ?

**Comment by adonespitogo** [comment]
Add `disabled`  attribute to the input element

**Comment by adonespitogo** [comment]
You can make use of `$rootScope.spinnerActive` to disable your UI while loading

**Comment by jgribonvald** [comment]
Is there a service property which can use instead ? $rootscope attributes should be avoided

**Comment by adonespitogo** [comment]
Not yet. This project was published when I just started out learning angularjs. Please feel free to create a pull request.

**Comment by jgribonvald** [comment]
A tip to do that without js code modification 
define a such css 
```
.overlay {
    background-color: #333; /*or semitransparent image*/
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 2000;
    opacity: 0.5;
}
```
and add class="overlay" to us-spinner span
